package com.csu.xgum.greendaod;

import com.csu.xgum.entity.NoteBook;
import com.csu.xgum.entity.Student;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteBookDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final NoteBookDao noteBookDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteBookDaoConfig = daoConfigMap.get(NoteBookDao.class).clone();
        noteBookDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        noteBookDao = new NoteBookDao(noteBookDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(NoteBook.class, noteBookDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        noteBookDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public NoteBookDao getNoteBookDao() {
        return noteBookDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
