package com.csu.xgum.greendaod;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.csu.xgum.greendaof.converter.StringDateConverter;
import java.util.Date;

import com.csu.xgum.entity.Student;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "student".
*/
public class StudentDao extends AbstractDao<Student, Long> {

    public static final String TABLENAME = "student";

    /**
     * Properties of entity Student.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "NAME");
        public final static Property StuId = new Property(1, Long.class, "stuId", true, "stuId");
        public final static Property StuNo = new Property(2, Long.class, "stuNo", false, "STU_NO");
        public final static Property Tall = new Property(3, String.class, "tall", false, "TALL");
        public final static Property Age = new Property(4, String.class, "age", false, "AGE");
        public final static Property Date = new Property(5, String.class, "date", false, "datetimen");
    }

    private final StringDateConverter dateConverter = new StringDateConverter();

    public StudentDao(DaoConfig config) {
        super(config);
    }
    
    public StudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"student\" (" + //
                "\"NAME\" TEXT NOT NULL ," + // 0: name
                "\"stuId\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 1: stuId
                "\"STU_NO\" INTEGER," + // 2: stuNo
                "\"TALL\" TEXT NOT NULL ," + // 3: tall
                "\"AGE\" TEXT NOT NULL ," + // 4: age
                "\"datetimen\" TEXT);"); // 5: date
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_student_STU_NO ON \"student\"" +
                " (\"STU_NO\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"student\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Student entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
 
        Long stuId = entity.getStuId();
        if (stuId != null) {
            stmt.bindLong(2, stuId);
        }
 
        Long stuNo = entity.getStuNo();
        if (stuNo != null) {
            stmt.bindLong(3, stuNo);
        }
        stmt.bindString(4, entity.getTall());
        stmt.bindString(5, entity.getAge());
 
        Date date = entity.getDate();
        if (date != null) {
            stmt.bindString(6, dateConverter.convertToDatabaseValue(date));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Student entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
 
        Long stuId = entity.getStuId();
        if (stuId != null) {
            stmt.bindLong(2, stuId);
        }
 
        Long stuNo = entity.getStuNo();
        if (stuNo != null) {
            stmt.bindLong(3, stuNo);
        }
        stmt.bindString(4, entity.getTall());
        stmt.bindString(5, entity.getAge());
 
        Date date = entity.getDate();
        if (date != null) {
            stmt.bindString(6, dateConverter.convertToDatabaseValue(date));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    @Override
    public Student readEntity(Cursor cursor, int offset) {
        Student entity = new Student( //
            cursor.getString(offset + 0), // name
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // stuId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // stuNo
            cursor.getString(offset + 3), // tall
            cursor.getString(offset + 4), // age
            cursor.isNull(offset + 5) ? null : dateConverter.convertToEntityProperty(cursor.getString(offset + 5)) // date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Student entity, int offset) {
        entity.setName(cursor.getString(offset + 0));
        entity.setStuId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setStuNo(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setTall(cursor.getString(offset + 3));
        entity.setAge(cursor.getString(offset + 4));
        entity.setDate(cursor.isNull(offset + 5) ? null : dateConverter.convertToEntityProperty(cursor.getString(offset + 5)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Student entity, long rowId) {
        entity.setStuId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Student entity) {
        if(entity != null) {
            return entity.getStuId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Student entity) {
        return entity.getStuId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
